import os

datasets = [
    'Clean_blood.csv', 'Clean_Breast_Cancer_Wisconsin.csv', 'Clean_covid.csv', 
    'Clean_creditcard.csv', 'Clean_DDos.csv', 'Clean_haberman.csv', 'Clean_heart.csv', 
    'Clean_Infiltration.csv', 'Clean_ionosphere.csv', 'Clean_Loan_Default.csv', 
    'Clean_nsl_kdd_full_dataset.csv', 'Clean_pimadiabetes.csv', 'Clean_shuttle_full_dataset.csv', 
    'Clean_Titanic-Dataset.csv', 'Clean_weatherAUS.csv'
]
methods = [
    'smote', 'gan_from_tutorial', 'gan_paper', 'gan_paper_2', 'wgangp', 'ctgan', 'smotified_gan'
]

run = 42
classifier = 'random_forest'

with open('resume_visualizations.sh', 'w') as f:
    f.write('#!/bin/bash\n\n')
    f.write('PYTHON_SCRIPT="main.py"\n\n')
    
    missing_cmds = 0
    for d in datasets:
        for m in methods:
            for use_iqr in [False, True]:
                dataset_name = d.replace('.csv', '')
                if use_iqr:
                    dataset_name = 'iqr_' + dataset_name
                
                # Output files generated by this process ('standard' and '_filtered' run in a single instance)
                # Verify if any output file is missing for either variant (standard or filtered)
                
                missing = False
                for variant in [m, f"{m}_filtered"]:
                    tsne = f'results/tsne_{dataset_name}_{variant}_rs42.pdf'
                    kendall = f'results/kendall_correlation/corr_kendall_{dataset_name}_{variant}.pdf'
                    
                    hist1 = f'results/feature_histograms/hist_compare_{dataset_name}_{m}.pdf'
                    hist2 = f'results/histograms/hist_compare_{dataset_name}_{m}.pdf'
                    
                    if not os.path.exists(tsne) or not os.path.exists(kendall) or not (os.path.exists(hist1) or os.path.exists(hist2)):
                        missing = True
                        break # If any artifact is missing, rerun the whole execution
                
                if missing:
                    missing_cmds += 1
                    iqr_flag = "--use_iqr_preprocessing" if use_iqr else ""
                    f.write(f'echo "Resume: Dataset={d}, Balance={m}, IQR={use_iqr}"\n')
                    f.write(f'python $PYTHON_SCRIPT --dataset "{d}" --balance "{m}" --classifier "{classifier}" --randomState "{run}" {iqr_flag} --skip_baseline --skip_classification --use_tsne --plot_histograms --plot_kendall_correlation\n\n')

print(f"Generated script resume_visualizations.sh. Missing runs to execute: {missing_cmds}")